Expt 02 IDSP: Write a python program to demonstrate indexing in numpy array.

In [6]:
import numpy as np

In [7]:
#A 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
# Accessing elements using indexing
print("Element at row 0, column 1:", arr[0, 1])  # Output: 2
print("Element at row 2, column 2:", arr[2, 2])  # Output: 9

Element at row 0, column 1: 2
Element at row 2, column 2: 9


In [9]:
# Slicing the array
print("First two rows and all columns:\n", arr[:2, :])

First two rows and all columns:
 [[1 2 3]
 [4 5 6]]


In [10]:
print("All rows and last two columns:\n", arr[:, 1:])

All rows and last two columns:
 [[2 3]
 [5 6]
 [8 9]]


In [11]:
# Using boolean indexing
print("Elements greater than 5:\n", arr[arr > 5])

Elements greater than 5:
 [6 7 8 9]
